# Generated by Django 5.0 on 2024-01-22 03:49

import cbahi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement_Policy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_Titel_AR', models.CharField(blank=True, max_length=200, null=True)),
                ('Policy_Titel_EN', models.CharField(blank=True, max_length=200, null=True)),
                ('Policy_description', models.TextField()),
                ('Policy_File', models.FileField(upload_to=cbahi.models.Path_Policy_File)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(blank=True, null=True)),
                ('Departemnt_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departemnts', verbose_name=' Departemnt Name | إسم القسم')),
                ('Site_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cloud_site', verbose_name=' Hospital Name | إسم المستشفى')),
            ],
            options={
                'verbose_name_plural': 'Departement_Policy | سياسات الأقسام ',
                'db_table': 'Quality_Departement_Policy',
            },
        ),
    ]
