# Generated by Django 5.0 on 2024-01-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operating_Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patiant_or_appointment',
            name='Operation_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation_Name', to='Operating_Room.operation_type'),
        ),
    ]
