# Generated by Django 5.0 on 2024-01-17 22:51

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name_ar', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Site_Name_ar')),
                ('Site_Name_en', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Site_Name_en')),
                ('Site_Logo', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=home.models.Path_Site_Logo)),
            ],
            options={
                'db_table': 'Cloud_Site',
            },
        ),
        migrations.CreateModel(
            name='DEPARTEMNTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AR_Name', models.CharField(blank=True, max_length=21, null=True)),
                ('EN_Name', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'db_table': 'DEPARTEMNTS_Site',
            },
        ),
    ]
