# Generated by Django 5.0 on 2024-01-17 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_site',
            name='Super_User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SuperUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departemnts',
            name='Manger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DepartementManger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departemnts',
            name='Site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cloud_site'),
        ),
    ]
