# Generated by Django 5.0 on 2024-01-22 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ovr_basemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_date', models.DateTimeField(auto_now=True)),
                ('creator_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contributing_Factors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contributing Factors | عوامل مساهمة',
                'db_table': 'Contributing_Factors',
            },
        ),
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Category | فئة الحدث ',
                'db_table': 'Event_Category',
            },
        ),
        migrations.CreateModel(
            name='Level_of_Harm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('risk_value', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Level of Harm |مستوى الضرر',
                'db_table': 'Level_of_Harm',
            },
        ),
        migrations.CreateModel(
            name='Likelihood_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('risk_value', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Likelihood Category | فئة الإحتمالية',
                'db_table': 'Likelihood_Category',
            },
        ),
        migrations.CreateModel(
            name='CONFIDENTIAL_OVR_tickit',
            fields=[
                ('ovr_basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ovr.ovr_basemodel')),
                ('Date_Time_of_Event', models.DateTimeField(auto_now=True, verbose_name='Event Date & Time تاريخ الحادثة والوقت')),
                ('Description', models.TextField(verbose_name='Description | نبذة مختصرة')),
                ('patient_type', models.CharField(blank=True, choices=[('Inpatient منوم', 'Inpatient منوم'), ('Outpatient عيادات خارجية أو طوارئ', 'Outpatient عيادات خارجية أو طوارئ'), ('Employee موظف', 'Employee موظف'), ('Visitor زائر', ' Visitor زائر')], default='Visitor زائر', max_length=100, null=True, verbose_name=' patient type | تصنيف المريض ')),
                ('Event_type', models.CharField(blank=True, choices=[('Incident حادث', 'Incident حادث'), ('Reportable Event حدث قابل للإبلاغ', 'Reportable Event حدث قابل للإبلاغ'), ('Sentinel Event حادث جسيم', 'Sentinel Event حادث جسيم'), ('Near Miss حادث وشيك', 'Near Miss حادث وشيك'), ('Unsafe Condition حالة غير آمنة', 'Unsafe Condition حالة غير آمنة')], max_length=200, null=True, verbose_name='Event type |نوع الحدث')),
                ('Injury_occurred', models.CharField(blank=True, choices=[('Physical جسدية', 'Physical جسدية'), ('psychological نفسية', 'psychological نفسية'), ('No injury لاتوجد', 'No injury لاتوجد')], max_length=20, null=True, verbose_name='Injury occurred? | هل من إصابات؟')),
                ('Risk_Classification', models.CharField(blank=True, max_length=20, null=True, verbose_name=' Risk Classification & Rating (Autofill) ')),
                ('Assign_dateTime', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Waiting for response', 'Waiting for response'), ('Assigned', 'Assigned'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Waiting for response', max_length=20)),
            ],
            options={
                'verbose_name_plural': ' OVR Tickit List ',
            },
            bases=('ovr.ovr_basemodel',),
        ),
        migrations.CreateModel(
            name='Quality_Departement_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departemnt_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departemnts', verbose_name=' Departemnt Name | إسم القسم')),
                ('Users_Access', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=' Users_Access  | الأعضاء المسؤولين ')),
            ],
            options={
                'verbose_name_plural': 'Quality Departement Service ',
                'db_table': 'Quality_Departement_Service',
            },
        ),
        migrations.CreateModel(
            name='Replay_Ovr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('Privet', models.BooleanField(default=False)),
                ('Replay_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Replay_User')),
                ('OVR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovr.confidential_ovr_tickit')),
            ],
            options={
                'db_table': 'Replay_Ovr',
            },
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Assign_To_Section',
            field=models.ManyToManyField(blank=True, to='ovr.quality_departement_service', verbose_name='Assign To Department / Section | إسناد إلى إدارة / قسم'),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Contributing_Factors',
            field=models.ManyToManyField(blank=True, to='ovr.contributing_factors', verbose_name=' Contributing Factors | عوامل مساهمة* '),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Event_Category',
            field=models.ManyToManyField(blank=True, related_name='Events_Category', to='ovr.event_category', verbose_name=' Event Category | فئة الحدث '),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Level_of_Harm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LevelofHarm', to='ovr.level_of_harm', verbose_name='Level of Harm |مستوى الضرر'),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Likelihood_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Likelihood_Category', to='ovr.likelihood_category', verbose_name='Likelihood Category | فئة الإحتمالية'),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='home.departemnts', verbose_name='Location | موقع الحادث'),
        ),
        migrations.AddField(
            model_name='confidential_ovr_tickit',
            name='section_accident_occurred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departemnts', verbose_name='Reporting Department / Section | إدارة مرسل التقرير '),
        ),
    ]
